name: Verify and Publish Provider Pact Results

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify-provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-cli


      - name: publish provider pacts
        run: |
          pact-broker publish-provider-contract \
          --provider "books-provider" \
          --provider-app-version "1.0.0" \
          --contract ./provider/swagger.yml \
          --contract-type "oas" \
          --content-type "application/yaml" \
          --broker-base-url https://yuvsmart.pactflow.io \
          --broker-token ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Run provider verification
        run: |
          # Example: using pact-js to verify pacts
          npm run test:provider
        env:
          PACT_BROKER_BASE_URL: https://yuvsmart.pactflow.io
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Publish verification result to PactFlow
        run: |
          npx pact-broker record-verify-result \
            --provider books-provider \
            --provider-version $GITHUB_SHA \
            --success true \
            --pact-url https://yuvsmart.pactflow.io/pacts/provider/books-provider/consumer/books-consumer/latest \
            --broker-base-url https://yuvsmart.pactflow.io \
            --broker-token ${{ secrets.PACT_BROKER_TOKEN }}