name: Verify and Publish Provider Pact Results

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify-provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-cli


      - name: Run provider 
        run: |
          # Example: using pact-js to verify pacts
          npm run run_provider

      - name: Run provider verification
        run: |
          # Example: using pact-js to verify pacts
          npm run run_provider_tests
        env:
          PACT_BROKER_BASE_URL: https://yuvsmart.pactflow.io
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: publish provider pacts
        run: |
          docker run --rm -v /${PWD}:/${PWD} -w ${PWD} \
          -e https://yuvsmart.pactflow.io \
          -e ${{ secrets.PACT_BROKER_TOKEN }} \
          pactfoundation/pact-cli:0.50.0.28 \
          pactflow publish-provider-contract \
          provider/swagger.yml \
          --provider "books-provider" \
          --provider-app-version 0.0.1 \
          --branch main \
          --content-type application/yaml \
          --verification-exit-code=0 \
          --verification-results test-results/results.xml \
          --verification-results-content-type text/plain \
          -verification-results-format junit \
          --verifier mocha