name: Verify and Publish Provider Pact Results

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify-provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-cli


      - name: Run provider 
        run: |
          # Example: using pact-js to verify pacts
          nohup npm run run_provider &> server.log &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            curl -sSf http://localhost:9000 && break
            echo "Waiting for server..."
            sleep 3
          done
      - name: Run provider verification
        run: |
          # Example: using pact-js to verify pacts
          npm run run_provider_tests
        env:
          PACT_BROKER_BASE_URL: https://yuvsmart.pactflow.io
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: publish provider pacts
        run: |
          docker run --rm -v /${PWD}:/${PWD} -w ${PWD} \
          -e PACT_BROKER_TOKEN=${{ secrets.PACT_BROKER_TOKEN }} \
          pactfoundation/pact-cli:latest \
          pactflow publish-provider-contract ./src/provider/swagger.yml --provider books-provider --provider-app-version 0.0.1  \
          --broker-base-url https://yuvsmart.pactflow.io \
          --branch main \
          --content-type application/yaml \
          --verification-exit-code 0 \
          --verification-results test-results/results.xml \
          --verification-results-content-type text/plain \
          --verification-results-format junit \
          --verifier postman

      - name: provider pact can-i-deploy check
        run: |
            docker run --rm -v /${PWD}:/${PWD} -w ${PWD} \
            -e PACT_BROKER_TOKEN=${{ secrets.PACT_BROKER_TOKEN }} \
            pactfoundation/pact-cli:latest \
            broker can-i-deploy --broker-base-url https://yuvsmart.pactflow.io --pacticipant book-provider --version 0.0.1 --to-environment production
        env:
          PACT_BROKER_BASE_URL: https://yuvsmart.pactflow.io
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}